export const HANDLE_INPUT_FOUCUS='header/handle_Input_Focus'
export const HANDLE_INPUT_BLUR='header/handle_Input_Blur'
export const HANDLE_GET_LIST='header/handle_Get_list'
export const GET_INIT_LIST='header/get_init_list'
export const MOUSE_ENTER='header/mouse_enter'
export const MOUSE_LEAVE='header/mouse_leave'
export const CHANGE_PAGE_LIST='header/change_page_list'
