export const SETTIME='write/settime'
export const CHANGEHEADER='write/changeHeader'
export const CHANGECONTENT='write/changeContent'
export const UPLOADPASSAGE='write/uploadPassage'
export const GETUPLOAD='write/getupload'